import { existsSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { basename, join, resolve } from "node:path";
import { Gui4CliError } from "../errors.js";
import type { FormSpec, FormValues } from "../schema/form.js";
import { writeWindowApp, type WindowPayload } from "./window.js";

export function slugify(title: string): string {
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "app";
}

export function defaultBuildDir(title: string, cwd: string): string {
  return resolve(cwd, `${slugify(title)}-gui`);
}

export async function writeBuildProject(input: {
  spec: FormSpec;
  values: FormValues;
  outDir: string;
  lastRunPath: string;
  force?: boolean;
}): Promise<string> {
  const outDir = resolve(input.outDir);
  await prepareOutDir(outDir, input.force === true);

  const payload: WindowPayload = {
    spec: input.spec,
    values: input.values,
    nodePath: process.execPath,
    lastRunPath: input.lastRunPath,
    platform: process.platform,
  };
  await writeWindowApp(payload, outDir);

  const width = input.spec.window?.width ?? 960;
  const height = input.spec.window?.height ?? 620;
  const pkgName = slugify(input.spec.title);
  await writeFile(
    join(outDir, "package.json"),
    `${JSON.stringify(
      {
        name: pkgName,
        private: true,
        type: "module",
        scripts: {
          start: `npx --yes windowd --title ${JSON.stringify(input.spec.title)} --width ${width} --height ${height}`,
        },
      },
      null,
      2,
    )}\n`,
    "utf8",
  );
  await writeFile(
    join(outDir, "runner.js"),
    `// GUI4CLI does not rewrite the original script.\nexport const scriptPath = ${JSON.stringify(input.spec.target)};\n`,
    "utf8",
  );
  await writeFile(join(outDir, "README.md"), projectReadme(input.spec), "utf8");
  return outDir;
}

async function prepareOutDir(outDir: string, force: boolean): Promise<void> {
  if (existsSync(outDir)) {
    const entries = await readdir(outDir).catch(() => null);
    if (entries === null) {
      throw new Gui4CliError(
        `Could not write the project folder.`,
        `${outDir} already exists and is not a folder.`,
      );
    }
    if (entries.length > 0 && !force) {
      throw new Gui4CliError(
        `The folder ${outDir} already exists.`,
        "Choose another --out path, or pass --force to replace it.",
      );
    }
    if (force) {
      await rm(outDir, { recursive: true, force: true });
    }
  }
  await mkdir(outDir, { recursive: true });
}

function projectReadme(spec: FormSpec): string {
  const script = basename(spec.target);
  return `# ${spec.title}

Desktop form generated by GUI4CLI. This folder is the GUI shell. It runs **${script}** in place and does not rewrite that file.

\`\`\`bash
npx --yes windowd
# or
npm start
\`\`\`

The first windowd launch may download the NW.js runtime (~200 MB).

If you move this folder, keep the original script at:

\`${spec.target}\`

A real \`.exe\` is not part of this step.
`;
}
